spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5

  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 1q2w3e4r5t
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: mysql

#使用H2控制台
#spring.h2.console.enabled=true
#H2连接配置
#spring.datasource.url=jdbc:h2:~/test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.username=sa
#spring.datasource.password=